apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-crypto
    namespace: longhorn-system
data:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:UWjZHMzDP7+iTPI8b960J/oKksfc2b7ulh+bbp5bRdkDGvyduege4LdhYdPUIbpfJNgs49xG56Ae+a4A5ph90u53GOXzx6Ki9jD8M6ufIpBSeq3qVdxTqw==,iv:LNJtbIi4517pF6SAsNoof1eFbJ4HScHY+DoHDEzFI7A=,tag:O1dC2KDHp/4b3TE7r+hlBQ==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:xqKTqlgJ3s4=,iv:cNEfPXxH0/cFq48O5acSbJGBa8nJ82OvJ4Udi4FjTfY=,tag:jcss+RSfVSJzqpGeES4l3Q==,type:str]
sops:
    age:
        - recipient: age1htmvqs7eq8k3q6dxr82n0ltu2lehm3j4wp0j37d2g7p6w5augp8qutdhu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNk5hUGI0bnJxTDJQZVlM
            MGliRUZRTThOT2lhUEU3MzRzelNoQWk2NkN3CnBISTM1MDR6YncwYXdVN2t0NCt6
            WURsWG9Pd3pPN2tHdFZrcmhZOWJUclEKLS0tIHFzYlpmZW5JZ2VkQW9pTEtpWE01
            R1dWSDI5UnJFb0ZEc3BWVmgrVVpMRUkKMuQ8EyZ48A0f/McB1O/WoAw/R1WBEocw
            o/MkxIqJvdTtyi9bK0bWWWEfIihLWWQjVJPjxwawd7sG83JQhEfiQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T16:21:12Z"
    mac: ENC[AES256_GCM,data:oYSqtyy8Hn3Bl2zM3oZZp6Um4/c5sE4e54kZiKX0WzkRKO4y+y4umlp20+d+Jhj/i9JDYbmw7ZiR+iGC9cnIJmexu/yMbhEXFB5NDSh/q1+aFKi95Z+h+E8oKEz6Y7atcil0B5nybPpM6OD0v2LnodpCYjGxfGce0e35mztpAfk=,iv:/RtF2ySACalTl49KaUyesLtANuclYgSu7r+9R47lpKY=,tag:ndXYhEZlO7MS4xoQaGth4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
