apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: paperless-ngx-env-secret
    namespace: paperless-ngx
data:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:QYvA1tRdGfi/IgsA/vDurg7Jp0q3eK9CEY1nNjOrt6N8iFHYWgOCBIrUqY8=,iv:ZGBzOX2MdS1n9S4VSHyB39RnPIeHYjQpB1rpBB43Xdo=,tag:+iPGCp95tF/3eNDQMaB7hA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:VTGk/On72WaqvBWCGfpTOs4aXE5R2bNVS6jAxmGXEbiqoG9Wcs/XqmLE7QA=,iv:5lk1P0vEx7VvpLpkbdZtEp9wXBmXEgBInVqmYoT0Zzs=,tag:CQ7NYg96OXciB1U7jdVf0w==,type:str]
sops:
    age:
        - recipient: age1htmvqs7eq8k3q6dxr82n0ltu2lehm3j4wp0j37d2g7p6w5augp8qutdhu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M3ZnOXZTS1MzTWVkZjNJ
            NGp5cjFIaVVaM0thcFA1YmFTSWQwSnV4WTFzCmZnV0NUL0JRQmJkTkdDMDNKckNH
            OGdKUkJENll1aWl3aTc0Slc3bE1PNTAKLS0tIHpINi9oek42ZUxsM3FOVXpSbmJr
            MzBaYVlHdDh1R2JVVDBDeUxBbE8rSVUK/cvb4Mbq1dAekfEEtLYEgkSFmlU7T6as
            FdvRMXVlyO7Buikmm6YSobsnna8fFSe7TmvZMjhtJhF+U1HOqzDhcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T09:14:18Z"
    mac: ENC[AES256_GCM,data:wM1pkZpeXObCN/l2D6s5Wtjf3Ad77BvReK6BNyeBKzgsVHkbHfczf0pwpUBL6vEPfrK28DSp2/cylHFr0SSTbwCcwZy6BYl6Qpg7Rd/b+umGdDd9APxvNIYkVKcL0chPEqzacK/LpEECEyB/cVeRBZQufDgtRNQSp+cUvzjgl34=,iv:dMU8G7yJfFowGjd+RRW0nNLI5b14cdqkY8hGZAcV9EE=,tag:YnnJSCoScvmYTmnn2nkVcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
