apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rwmarkable-env-secret
    namespace: rwmarkable
data:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lgZwa6IhFG0pY4AXl0Kd9CqCxWFmpzsosEFPADcQVI35VdQ9oQOxn4zs+BYHLUQnPpPOL3teG7+Iwym28WZRx+7MEYYYM2aBEsnXAVCrGDIe7yZYT6+7caB/1zx7ru7Q,iv:v0FjRf7noLQXyCD8HatBnG41m+jnT0vq2VCW7NIwq2E=,tag:DOlQUDryoTM3FWk+jKDqqg==,type:str]
sops:
    age:
        - recipient: age1htmvqs7eq8k3q6dxr82n0ltu2lehm3j4wp0j37d2g7p6w5augp8qutdhu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ2tMV0doNlJFVldqSnk5
            QVBiQ1dNeHM0NFhVM3NXWjc5aVYzMDBrSndBCkhIeFcxRGR2VU1xcEJReHhFZ1Uv
            c3pGTWZzYXZzaXR2c1Nqcm9TRHNLSmcKLS0tIHhNeXZQQmJheXdjUXZnVkVUM2hJ
            dzJMS0RpQjZNM0JjYmhzQ1VsODdGcFEKlP8l2aFYXy+HqD+IMXI+AnpSzXo3n3+7
            Fnci5Cbd3JAi0/A1kVonflKImMwR16TnbA6m905BzrGi33g6lPFgEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T06:42:58Z"
    mac: ENC[AES256_GCM,data:puUPMGDHgg5I69njVGLf3HwZkFj15hZqqbhPnGjGqsIilMtDRQ8O/30FycjIYnZc/d2fTVMk9yU9ZaP3Gk/+YPoI5BDo1AfXBh47FqCP7RzKh2DMqgXae9VJOpUtDDjrNVvOUugCCXNBws4TdL9uiH9q4vCJOtoK7NNki859Up0=,iv:0zA0P5WcNXTyVXfMBsRwbYivefrwth4U7JNVeZOly/k=,tag:4epb8DjB/koCT0WZPWu/bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
