apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-encrypted-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn-crypto-global
