apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rwmarkable
  namespace: rwmarkable
spec:
  serviceName: rwmarkable
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rwmarkable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rwmarkable
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: rwmarkable
          image: ghcr.io/fccview/rwmarkable:1.6.1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: config
              mountPath: /app/config
          env:
            - name: NODE_ENV
              value: production
      volumes:
        - name: config
          configMap:
            name: rwmarkable-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
