---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: 0.7.5
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: flux-system
  interval: 1m0s
  releaseName: cert-manager-webhook-ovh
  targetNamespace: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: webhook-ovh-values
      valuesKey: values.yaml
