---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh
  namespace: flux-system
spec:
  interval: 5m
  url: https://aureq.github.io/cert-manager-webhook-ovh/
