apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: paperless-ngx
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: paperless-ngx
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: shmem
              mountPath: /dev/shm
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: paperless-ngx-env
                  key: PAPERLESS_DBUSER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: paperless-ngx-env
                  key: PAPERLESS_DBNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-env-secret
                  key: PAPERLESS_DBPASS
      volumes:
        - name: shmem
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
